# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
r_github_packages: jimhester/covr
matrix:
  include:
  - pandoc: false
    r: release
  - r_github_packages:
    - tidyverse/dplyr
    - jimhester/covr
    r: release
after_success:
  - Rscript -e '
Sys.setenv(COVERAGE="yes")
all_created <- c(huxtable:::huxtable_cell_attrs, huxtable:::huxtable_col_attrs,
huxtable:::huxtable_row_attrs, huxtable:::huxtable_table_attrs)
all_created <- paste0("^", all_created)
cov <- covr::package_coverage(function_exclusions = all_created)
covr::codecov(coverage = cov)
Sys.unsetenv("COVERAGE")
'
